# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190329_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=400)),
            ],
        ),
    ]
